#ifndef SYNTAXKIND_H
#define SYNTAXKIND_H

typedef enum {
    AST_COMPILATION_UNIT,
    AST_USE,
    AST_ATTR_DECL,
    AST_FUNC_DECL,
    AST_IDENT,
    AST_RETURN_STATEMENT,// 5
    AST_BINARY_EXPRESSION,
    AST_LOCAL_DECL,
    AST_FUNC_CALL,
    AST_IF_STATEMENT,
    AST_LITERAL,// 10
    AST_BLOCK,
    AST_ANNOTATE_LOCAL,
    AST_BIND_ANNO,
} SyntaxKind;

#endif