//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/Redstar.Parse/Redstar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Redstar.Parse {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRedstarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RedstarBaseListener : IRedstarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] RedstarParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] RedstarParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] RedstarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] RedstarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.attrDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrDecl([NotNull] RedstarParser.AttrDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.attrDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrDecl([NotNull] RedstarParser.AttrDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.annoDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnoDecl([NotNull] RedstarParser.AnnoDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.annoDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnoDecl([NotNull] RedstarParser.AnnoDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.bindDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindDecl([NotNull] RedstarParser.BindDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.bindDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindDecl([NotNull] RedstarParser.BindDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.bindAnnoConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindAnnoConstraint([NotNull] RedstarParser.BindAnnoConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.bindAnnoConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindAnnoConstraint([NotNull] RedstarParser.BindAnnoConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.bindAnnoLists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindAnnoLists([NotNull] RedstarParser.BindAnnoListsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.bindAnnoLists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindAnnoLists([NotNull] RedstarParser.BindAnnoListsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.bindAnnoAttrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindAnnoAttrList([NotNull] RedstarParser.BindAnnoAttrListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.bindAnnoAttrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindAnnoAttrList([NotNull] RedstarParser.BindAnnoAttrListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] RedstarParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] RedstarParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.funcParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParameters([NotNull] RedstarParser.FuncParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.funcParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParameters([NotNull] RedstarParser.FuncParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.funcParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParameter([NotNull] RedstarParser.FuncParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.funcParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParameter([NotNull] RedstarParser.FuncParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.funcReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncReturn([NotNull] RedstarParser.FuncReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.funcReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncReturn([NotNull] RedstarParser.FuncReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] RedstarParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] RedstarParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] RedstarParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] RedstarParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.attrAppl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrAppl([NotNull] RedstarParser.AttrApplContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.attrAppl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrAppl([NotNull] RedstarParser.AttrApplContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] RedstarParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] RedstarParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.binaryExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryExp([NotNull] RedstarParser.BinaryExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.binaryExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryExp([NotNull] RedstarParser.BinaryExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] RedstarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] RedstarParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.varDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDefine([NotNull] RedstarParser.VarDefineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.varDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDefine([NotNull] RedstarParser.VarDefineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.attrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrList([NotNull] RedstarParser.AttrListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.attrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrList([NotNull] RedstarParser.AttrListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] RedstarParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] RedstarParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.operands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperands([NotNull] RedstarParser.OperandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.operands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperands([NotNull] RedstarParser.OperandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] RedstarParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] RedstarParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] RedstarParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] RedstarParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralString([NotNull] RedstarParser.LiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralString([NotNull] RedstarParser.LiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.literalInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralInt([NotNull] RedstarParser.LiteralIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.literalInt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralInt([NotNull] RedstarParser.LiteralIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.literalDecimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralDecimal([NotNull] RedstarParser.LiteralDecimalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.literalDecimal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralDecimal([NotNull] RedstarParser.LiteralDecimalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypename([NotNull] RedstarParser.TypenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypename([NotNull] RedstarParser.TypenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] RedstarParser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] RedstarParser.IdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RedstarParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp([NotNull] RedstarParser.OpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RedstarParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp([NotNull] RedstarParser.OpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Redstar.Parse
